# Generated by Django 3.2.3 on 2021-12-04 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('affiliate_link', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('companyType', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'unique_together': {('name', 'affiliate_link', 'twitter', 'logo')},
            },
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='images/')),
                ('catagorey', models.CharField(blank=True, max_length=60, null=True)),
                ('smartContractAddress', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('asset_platform', models.CharField(blank=True, max_length=60, null=True)),
                ('initialMarketCap', models.FloatField(blank=True, null=True)),
                ('initialPrice', models.FloatField(blank=True, null=True)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoliotrack.company')),
            ],
            options={
                'unique_together': {('company', 'name', 'url', 'image', 'catagorey', 'smartContractAddress', 'asset_platform', 'initialMarketCap', 'initialPrice')},
            },
        ),
    ]
