# Generated by Django 3.2.3 on 2021-12-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliotrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyType',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
