# Generated by Django 3.2.3 on 2021-12-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliotrack', '0003_alter_company_companytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
