# Generated by Django 3.2.3 on 2021-12-05 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliotrack', '0004_alter_assets_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='affiliate_link',
            new_name='affiliateLink',
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('name', 'affiliateLink', 'twitter', 'logo', 'companyType')},
        ),
    ]
