# Generated by Django 3.2.3 on 2021-12-07 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliotrack', '0005_auto_20211204_2320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assets',
            new_name='Asset',
        ),
    ]
