# Generated by Django 3.2.3 on 2022-01-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliotrack', '0009_alter_asset_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='company',
        ),
        migrations.AddField(
            model_name='asset',
            name='company',
            field=models.ManyToManyField(to='portfoliotrack.Company'),
        ),
    ]
