# Generated by Django 3.2.3 on 2022-01-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliotrack', '0010_auto_20220102_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
