# Generated by Django 3.2.3 on 2022-01-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliotrack', '0011_alter_asset_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='catagorey',
            new_name='category',
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('name', 'url', 'image', 'category', 'smartContractAddress', 'asset_platform', 'initialMarketCap', 'initialPrice')},
        ),
    ]
