# Generated by Django 3.2.3 on 2022-01-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliotrack', '0012_auto_20220102_0441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='initialMarketCap',
            new_name='currentMarketCap',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='initialPrice',
            new_name='currentPrice',
        ),
        migrations.AddField(
            model_name='asset',
            name='lastMonthMarketCap',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('name', 'url', 'image', 'category', 'smartContractAddress', 'asset_platform')},
        ),
    ]
