# Generated by Django 3.2.3 on 2022-01-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliotrack', '0013_auto_20220105_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='coinId',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='dailyChange',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='currentMarketCap',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='currentPrice',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
