# Generated by Django 3.2.3 on 2022-01-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliotrack', '0015_rename_lastmonthmarketcap_asset_monthlychange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('name', 'url', 'image', 'smartContractAddress', 'asset_platform')},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='category',
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ManyToManyField(to='portfoliotrack.Category'),
        ),
    ]
