# Generated by Django 3.2.3 on 2022-01-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliotrack', '0016_auto_20220106_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_platform',
            new_name='assetPlatform',
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ManyToManyField(null=True, to='portfoliotrack.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('name', 'url', 'image', 'smartContractAddress', 'assetPlatform')},
        ),
    ]
