# Generated by Django 3.2.3 on 2022-01-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliotrack', '0017_auto_20220106_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tag',
            field=models.CharField(blank=True, max_length=600, null=True, unique=True),
        ),
    ]
